[package]
name = "geofabrik-downloader"
version = "0.1.0"
description = "Geofabrik PBF downloader - CLI tool and library for downloading OpenStreetMap data"
authors = ["Pierre <pierre@warnier.net>"]
license = "MIT"
repository = "https://github.com/username/butterfly"
keywords = ["osm", "geofabrik", "pbf", "openstreetmap", "download"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "gzip", "brotli", "stream", "rustls-tls"] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
indicatif = "0.17"
futures-util = "0.3"
log = "0.4"
env_logger = "0.10"
config = "0.13"
serde_yaml = "0.9"
futures = "0.3"
bytes = "1.0"
lazy_static = "1.4"
once_cell = "1.19"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.0"
