[package]
name = "butterfly-dl"
version = "0.1.0"
description = "Butterfly-dl - Optimized OpenStreetMap data downloader with S3 and HTTP support"
authors = ["Pierre <pierre@warnier.net>"]
license = "MIT"
repository = "https://github.com/username/butterfly"
keywords = ["osm", "geofabrik", "pbf", "openstreetmap", "download"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "gzip", "brotli", "stream", "rustls-tls"] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
indicatif = "0.17"
futures-util = "0.3"
log = "0.4"
env_logger = "0.10"
futures = "0.3"
bytes = "1.0"
once_cell = "1.19"
aws-config = "1.0"
aws-sdk-s3 = "1.0"
libc = "0.2"
num_cpus = "1.0"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.0"
