services:
  # Production image: FROM scratch (13.4MB)
  # Minimal, secure, optimized for deployment
  geofabrik-downloader:
    build: .
    container_name: geofabrik-downloader
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RENEW_PBF_PERIOD=${RENEW_PBF_PERIOD:-7}
    volumes:
      - ./data:/data
    working_dir: /data
    # Override entrypoint for interactive use
    # docker-compose run --rm geofabrik-downloader --help

  # Development image: Alpine + Rust + tools (~500MB+)  
  # Full toolchain for debugging and development
  geofabrik-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: geofabrik-dev
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RENEW_PBF_PERIOD=${RENEW_PBF_PERIOD:-7}
    volumes:
      - ./data:/data
      - .:/app
    working_dir: /app